### ISSUE TITLE
[1.19.2] Vertical slabs get culled when facing X axis and there's something next to them

### ISSUE THREAD

**Issue by No3371** [JackGlobetrotter/Full-Slabs#9]
![javaw_MohANLNYTB](https://github.com/JackGlobetrotter/Full-Slabs/assets/1814971/a7926401-5a43-4b63-8073-66a6043eba54)

![javaw_npWJ30qvNn](https://github.com/JackGlobetrotter/Full-Slabs/assets/1814971/224f9796-dd54-4018-9f1c-91bfdc5fed97)

![javaw_wcDLYrCFhU](https://github.com/JackGlobetrotter/Full-Slabs/assets/1814971/6e29c701-316b-4323-aded-6bc1b864b12e)

I have iris but it doesn't matter if shaders are enabled.
I also have some optimization mods, and I may continue to try to find if there are conflicting ones.
Just post this in case you may have a clue of what's going on.

**Comment by No3371** [comment]
Ah, I see it's an old issue. https://github.com/Micalobia/Full-Slabs/issues/72.

**Comment by JackGlobetrotter** [comment]
Known issue, should be fixed by commit [3ae00f](https://github.com/JackGlobetrotter/Full-Slabs/commit/13ae00f55a2b8eae2c2f89430d0b5dff39a824fc) 
Please try the mod version referenced here: #5 
Will be included in next release

**Comment by in-op** [comment]
Hi, I came here because I've been having this exact problem with Sodium + Full Slabs. The 3.3.10 version linked crashes my game on start:

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'full_slabs'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:459)
	at net.minecraft.client.main.Main.method_44604(Main.java:205)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_7922
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 8 more
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_7922
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 14 more
```

It crashes even with only these 3 mods: full slabs, cloth config, and fabric api (all the latest versions for 1.19.2). I tried on fabric loader 0.14.19 through 0.14.21 - they all had the same error.

**Comment by JackGlobetrotter** [comment]
sorry mod was compiled for 1.19.3, fix will be included in 3.40 release for 1.20.1 release
